from typing import Any

from langchain_community.utilities import SQLDatabase
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from app.config import settings

pool = ConnectionPool(
    conninfo=settings.postgres_url,
    min_size=1,
    max_size=5,
    kwargs={"row_factory": dict_row},
)


CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS employee_leave (
    id BIGSERIAL PRIMARY KEY,
    employee_name TEXT NOT NULL,
    department TEXT,
    position TEXT,
    leave_type TEXT,
    start_date DATE,
    end_date DATE,
    days_taken INTEGER,
    total_leave_entitlement INTEGER,
    leave_taken_so_far INTEGER,
    remaining_leaves INTEGER,
    month TEXT
);

CREATE INDEX IF NOT EXISTS idx_employee_leave_name
ON employee_leave(employee_name);

CREATE INDEX IF NOT EXISTS idx_employee_leave_department
ON employee_leave(department);
"""


def initialize_database() -> None:
    with pool.connection() as conn:
        with conn.cursor() as cur:
            cur.execute(CREATE_TABLE_SQL)
        conn.commit()


def clear_employee_data() -> None:
    with pool.connection() as conn:
        with conn.cursor() as cur:
            cur.execute("TRUNCATE TABLE employee_leave RESTART IDENTITY")
        conn.commit()


def insert_employee_rows(rows: list[dict[str, Any]]) -> None:
    sql = """
    INSERT INTO employee_leave (
        employee_name,
        department,
        position,
        leave_type,
        start_date,
        end_date,
        days_taken,
        total_leave_entitlement,
        leave_taken_so_far,
        remaining_leaves,
        month
    )
    VALUES (
        %(employee_name)s,
        %(department)s,
        %(position)s,
        %(leave_type)s,
        %(start_date)s,
        %(end_date)s,
        %(days_taken)s,
        %(total_leave_entitlement)s,
        %(leave_taken_so_far)s,
        %(remaining_leaves)s,
        %(month)s
    )
    """

    with pool.connection() as conn:
        with conn.cursor() as cur:
            cur.executemany(sql, rows)
        conn.commit()


def execute_read_query(sql: str) -> list[dict[str, Any]]:
    """
    Execute a read-only SQL query generated by the LLM.

    SQL validation happens before this function is called.
    """
    with pool.connection() as conn, conn.cursor() as cur:
        cur.execute(sql)
        return cur.fetchall()


def get_langchain_database() -> SQLDatabase:
    """
    Create a LangChain SQLDatabase wrapper around PostgreSQL
    using Psycopg 3.
    """
    sqlalchemy_url = settings.postgres_url.replace(
        "postgresql://",
        "postgresql+psycopg://",
        1,
    )

    return SQLDatabase.from_uri(sqlalchemy_url)